#!/bin/sh

# Desktop Login sound
paplay ~/.config/labwc/sound/desktop-login.oga >/dev/null 2>&1 &

# Start LXQt panel
lxqt-panel >/dev/null 2>&1 &

# Kill any LXQt desktop manager so Labwc gets right-click
# Delay needed because LXQt starts pcmanfm-qt AFTER labwc autostart
(sleep 3 && killall pcmanfm-qt 2>/dev/null) &

# Device plugged audio
bash ~/.config/labwc/scripts/device-monitor.sh >/dev/null 2>&1 &

# Set background (swww for animated, or swaybg for static)
# swww-daemon >/dev/null 2>&1 &

# Keyring
/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh >/dev/null 2>&1 &

# Polkit 
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 >/dev/null 2>&1 &

# Gtk Theme Refresh (also handled by systemd labwc-gtk-sync.service)
# bash ~/.config/labwc/scripts/gtk.sh >/dev/null 2>&1 &

# Clipboard
wl-clip-persist --clipboard regular &
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Set wallpaper (replace with your preferred method)
swaybg -c "#141c21" &

# Notification 
dunst >/dev/null 2>&1 &

# Idle device manager
swayidle -w \
    timeout 300 "~/.config/labwc/idle/brightness_ctrl.sh --fade-out" \
    resume "~/.config/labwc/idle/brightness_ctrl.sh --fade-in" \
    timeout 600 "loginctl lock-session" \
    timeout 1800 "systemctl suspend" \
    lock "~/.config/labwc/idle/lock_ctrl.sh" \
    before-sleep "~/.config/labwc/idle/sleep_ctrl.sh" \
    after-resume "~/.config/labwc/idle/brightness_ctrl.sh --fade-in" \
    >/dev/null 2>&1 &

